@startuml

entity members {
    id
    --
    * name
    task_id
}

entity membertasks {
    id
    --
    name
}

entity Orders {
    id
    --
    customer_name
    customer_email
    order_date
}

entity OrderLines {
    member_id
    order_id
    --
    quantity
}

membertasks ||--o{ members
members ||-o{ OrderLines
OrderLines }o-|| Orders

@enduml